- name: Install apache
  hosts: all
  become: yes

  tasks:
  - name: Install prerequisites
    apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

  - name: Install Apache2
    apt: name=apache2 update_cache=yes state=latest

  - name: Copy index test page
    template:
      src: "./website/index.html.j2"
      dest: "/var/www/html/index.html"
    notify: Restart Apache
    
  - name: Start apache
    service: name=apache2 state=started

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted